package edu.kit.scholarizer;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main class of the Scholarizer application.
 * @author Auto-generated by Spring Boot
 * @version 1.0
 */
@SpringBootApplication
public class ScholarizerApplication {

    /**
     * Main method of the Scholarizer application.
     * @param args the arguments of the main method
     */
    public static void main(String[] args) {
        SpringApplication.run(ScholarizerApplication.class, args);
    }

}
